name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore: [ '*.md', 'assets/**', 'LICENSE', CHANGELOG.md ]
    branches: [ 'feature/**', "release/**", "bug/**", "issue/**" ]
  pull_request:
    paths-ignore: [ '*.md', 'assets/**', 'LICENSE', CHANGELOG.md ]
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
